
# NOTES:
# - This file is symlinked, so all paths in this file need to either be absolute or relative to "/home/unms/app/".
# - The version in the 'image' name and the 'UCRM_VERSION' arg will be updated by the 'build' provisioner, as needed.

version: "2"

services:
    postgres:
        networks:
            - public
        ports:
            - "5432:5432"
    ucrm:
        image: ubnt/unms-crm:3.4.6-xdebug
        build:
            context: ./overrides/ucrm
            dockerfile: Dockerfile
            args:
              UCRM_VERSION: 3.4.6
        volumes:
            - ./overrides/ucrm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./overrides/ucrm/xdebug_params:/etc/nginx/xdebug_params
            - ../../vagrant/scripts/ucrm:/scripts
