# -*- mode: ruby -*-
# vi: set ft=ruby :

require "rbconfig"

Vagrant.configure("2") do |config|

    # ------------------------------------------------------------------------------------------------------------------
    # CONFIGURATION
    # ------------------------------------------------------------------------------------------------------------------

    # Override the following defaults as desired:
    ROOT_PASSWORD   = "vagrant"
    UISP_VERSION    = "1.4.6"

    # ------------------------------------------------------------------------------------------------------------------
    # NETWORKING
    # ------------------------------------------------------------------------------------------------------------------

    config.vm.hostname = "uisp"

    # ------------------------------------------------------------------------------------------------------------------
    # FILE SYSTEM
    # ------------------------------------------------------------------------------------------------------------------

    # Disable the default synced folder.
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # ------------------------------------------------------------------------------------------------------------------
    # BASE BOX
    # ------------------------------------------------------------------------------------------------------------------

    # Use an Ubuntu base box.
    config.vm.box = "bento/ubuntu-20.04"

    # ------------------------------------------------------------------------------------------------------------------
    # PROVIDERS
    # ------------------------------------------------------------------------------------------------------------------

    # VirtualBox
    config.vm.provider "virtualbox" do |vm|
        vm.name = "uisp-#{UISP_VERSION}"

        # NOTE: Set the following to suit your needs and based upon available host resources.
        vm.cpus = 1
        vm.memory = 2048
    end

    # VMware
    # NOTE: Issues when packaging the box, more work later.
    #config.vm.provider "vmware_desktop" do |vm|
    #    #vm.gui = true
    #    vm.vmx["displayname"] = "uisp-#{UISP_VERSION}"
    #
    #    # NOTE: Set the following to suit your needs and based upon available host resources.
    #    vm.vmx["memsize"] = "4096"
    #    vm.vmx["numvcpus"] = "1"
    #end

    # Hyper-V
    # NOTE: Issues with synced folders, more work later.
    #config.vm.provider "hyperv" do |vm, override|
    #    vm.vmname = "uisp-#{UISP_VERSION}"
    #
    #    # NOTE: Set the following to suit your needs and based upon available host resources.
    #    vm.cpus = "1"
    #    vm.memory = "4096"
    #    vm.maxmemory = "8192"
    #
    #    # NOTE: This is used to skip the Switch prompt, change as needed; OR simply remove completely to be prompted.
    #    override.vm.network "private_network", bridge: "Default Switch"
    #end

    # ------------------------------------------------------------------------------------------------------------------
    # PROVISIONERS
    # ------------------------------------------------------------------------------------------------------------------

    # Provision the Users...
    config.vm.provision "users", type: "shell", keep_color: true,
        path: "./vagrant/provisioning/base/users.sh",
        env: { "ROOT_PASSWORD" => "#{ROOT_PASSWORD}" }

    # Provision the Network...
    config.vm.provision "network", type: "shell", keep_color: true,
        path: "./vagrant/provisioning/base/network.sh",
        env: { "IPV6_DISABLE" => "all,default,lo,eth0" }

    # Provision the Firewall...
    config.vm.provision "firewall", type: "shell", keep_color: true,
        path: "./vagrant/provisioning/base/firewall.sh",
        env: { }

    # Provision the UISP installation...
    config.vm.provision "install", type: "shell", keep_color: true,
        path: "./vagrant/provisioning/base/install.sh",
        env: { "UISP_VERSION" => "#{UISP_VERSION}" }

    # Provision file/folder permissions...
    config.vm.provision "permissions", type: "shell", keep_color: true,
        path: "./vagrant/provisioning/base/permissions.sh",
        env: { }
end
